### ISSUE TITLE
WILLIAM READ THIS

### ISSUE THREAD

**Issue by ls998** [Fungucide/friendshiptactoe#3]
IM UPDATING THE  CODE FOR THE AI!!!!!!!!!!
so you shouldn't change anything until im done (check for a new commit called "updated ai to framework:")
IF YOU DON"T GET WHAT I CHANGED, READ THE DOCUMENTATIon i made

OH YEAH, AND CHECK OUT THE CLASS CALLED `RowWinRule` (its in the branch `gamelogicmodule`)
 - it has code for detecting stuff in a row (so you can read it to see how it works)

**Comment by ls998** [comment]
ALSO< I FINISHED THE CHECK FOR ROWS THING FOR YOU

**Comment by ls998** [comment]
when i'm done, i'll merge the frameworkupdate branch to the master branch (meaning all my framework updating is also applied into the master branch)

i'll delete the frameworkupdate branch, since im done updating the framework

_**# you need to merge the master branch into your ai branch, since that'll apply all the changes i made into your branch**_

**Comment by ls998** [comment]
ill explain all the merging stuff on monday

just make sure you pull before you do anything

**Comment by Fungucide** [comment]
K
