### ISSUE TITLE
Merging stuff Is giving errors

### ISSUE THREAD

**Issue by Fungucide** [Fungucide/friendshiptactoe#6]
My eclipse says that there are merge errors and I cannot update my stuff

**Comment by ls998** [comment]
what are you merging?

**Comment by Fungucide** [comment]
Ummm... I deleted the whole project and tried to re-update it but it is not updating :( Pls save.I tried pulling from stream but it is not pulling

**Comment by ls998** [comment]
WHY DID YOU DELETE IT?? NOW YOU HAVE TO RE SETUP ALL THE STUFF
Heres the steps:
1. Delete project
2. Delete repository (on computer)
3.

**Comment by Fungucide** [comment]
K got everything to work now :)

**Comment by ls998** [comment]
Did you follow my instructions?

**Comment by Fungucide** [comment]
Yup

**Comment by Fungucide** [comment]
I can't see the AI branch

**Comment by ls998** [comment]
which branch?

**Comment by Fungucide** [comment]
AI branch

**Comment by ls998** [comment]
did you check in the switch branch>other...?
 LOOK CAREFULLY THERE

AND PULL FRIST

**Comment by Fungucide** [comment]
RIght

**Comment by ls998** [comment]
whats the math homework?

**Comment by ls998** [comment]
finally
